apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "capacity.fullname" . }}-config
  labels:
    app.kubernetes.io/name: {{ template "capacity.name" . }}
{{ include "capacity.labels" . | indent 4 }}
data:
  kubescaler.conf: |
    {{ .Values.config.kubescaler.raw }}
  userdata: |
    {{ .Values.config.userdata }}