{{- if and .Values.rbac.create .Values.serviceAccount.create }}
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ template "capacity.name" . }}-configmap
  labels:
    app.kubernetes.io/name: {{ template "capacity.name" . }}
{{ include "capacity.labels" . | indent 4 }}
subjects:
- kind: ServiceAccount
  name: {{ template "capacity.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: {{ template "capacity.name" . }}-configmap-updater
  apiGroup: rbac.authorization.k8s.io
{{- end }}