{{- if and .Values.rbac.create .Values.serviceAccount.create }}
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ template "capacity.name" . }}-configmap-updater
  labels:
    app.kubernetes.io/name: {{ template "capacity.name" . }}
{{ include "capacity.labels" . | indent 4 }}
rules:
- apiGroups: [""]
  resources: ["configmaps"]
  resourceNames: ['{{ template "capacity.fullname" . }}-config']
  verbs: ["get", "patch"]
{{- end }}