{{- if and .Values.rbac.create .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "capacity.serviceAccountName" . }}
  labels:
    app.kubernetes.io/name: {{ template "capacity.name" . }}
{{ include "capacity.labels" . | indent 4 }}
{{- end }}